spring:
  application:
    name: eureka-server
  freemarker:
    prefer-file-system-access: true


server:
  port: 8761  #\u9ED8\u8BA4\u662F8080

eureka:
  instance:
    hostname: localhost  #eureka\u5B9E\u4F8B\u7684\u4E3B\u673A
  client:
    register-with-eureka: false  #\u8868\u793A\u662F\u5426\u5C06\u81EA\u5DF1\u6CE8\u518C\u5230Eureka Server\u4E0A\uFF0C\u9ED8\u8BA4\u4E3Atrue
    fetch-registry: false    #\u8868\u793A\u662F\u5426\u4ECEEureka Server\u4E0A\u83B7\u53D6\u6CE8\u518C\u4FE1\u606F\uFF0C\u9ED8\u8BA4\u4E3Atrue ,\u8FD9\u4E24\u4E2A\u914D\u7F6E\u5C31\u8868\u793A\u8FD9\u662F\u670D\u52A1\u7AEF\u800C\u4E0D\u662F\u5BA2\u6237\u7AEF
  serviceUrl:
        defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
